package com.filrouge.restaurantcore.dao;
import java.util.Optional;

import org.springframework.data.mongodb.repository.MongoRepository;

import com.filrouge.restaurantcore.dto.IngredientDto;
import com.filrouge.restaurantcore.entity.IngredientRecipe;

/**
 * Personalized DAO services for Ingredient.
 * @author FAndre
 *
 */
public interface IIngredientRecipeRepository extends MongoRepository<IngredientRecipe, String>{
	//The key is of type String for an identifier using the @MongoId annotation (FieldType.OBJECT_ID)
    //The key is automatically generated by MongoDB
	
	boolean existsByQuantityAndIngredient (int quantity, IngredientDto dto);
	
	Optional<IngredientRecipe> findFirstByQuantityAndIngredient (int quantity, IngredientDto dto);

}
