package com.filrouge.restaurantcore.dao;

<<<<<<< HEAD


=======
>>>>>>> d98e6705b0ce00c8b2b8bb3cda30bef15d59e7f5
import org.springframework.data.mongodb.repository.MongoRepository;

import com.filrouge.restaurantcore.entity.IngredientRecipe;

<<<<<<< HEAD


public interface IIngredientRecipeRepository extends MongoRepository<IngredientRecipe, String>{
	//The key is of type String for an identifier using the @MongoId annotation (FieldType.OBJECT_ID)
    //The key is automatically generated by MongoDB
	
	
	

=======
/**
 * Personalized DAO services for Ingredient.
 * @author FAndre
 *
 */

public interface IIngredientRecipeRepository extends MongoRepository<IngredientRecipe, String> {
	


>>>>>>> d98e6705b0ce00c8b2b8bb3cda30bef15d59e7f5
}
