package com.filrouge.restaurantcore.dao;

import org.springframework.data.mongodb.repository.MongoRepository;

import com.filrouge.restaurantcore.entity.Ingredient;

/**
 * Personalized DAO services for Ingredient.
 * @author Hermann
 *
 */

public interface IIngredientRepository extends MongoRepository<Ingredient, String>{
	//The key is of type String for an identifier using the @MongoId annotation (FieldType.OBJECT_ID)
    //The key is automatically generated by MongoDB
	
}
