package com.filrouge.restaurantcore.dao;



import org.springframework.data.mongodb.repository.MongoRepository;

import com.filrouge.restaurantcore.entity.IngredientRecipe;



public interface IIngredientRecipeRepository extends MongoRepository<IngredientRecipe, String>{
	//The key is of type String for an identifier using the @MongoId annotation (FieldType.OBJECT_ID)
    //The key is automatically generated by MongoDB
	
	
	

}
