package com.filrouge.restaurantcore.dao;

import java.util.List;

import org.springframework.data.mongodb.repository.MongoRepository;

import com.filrouge.restaurantcore.entity.Ingredient;
import com.filrouge.restaurantcore.entity.Recipe;
import com.filrouge.restaurantcore.entity.User;

/**
 * Personalized DAO services for Recipe.
 * @author Hermann
 *
 */

public interface IRecipeRepository extends MongoRepository<Recipe, String>{
	//The key is of type String for an identifier using the @MongoId annotation (FieldType.OBJECT_ID)
    //The key is automatically generated by MongoDB
	
	 List<Recipe> findByName(String name);
	
	
	

}
