package com.filrouge.restaurantcore.dao;

import java.util.List;
import java.util.Optional;

import org.springframework.data.mongodb.repository.MongoRepository;
import org.springframework.data.mongodb.repository.Query;

import com.filrouge.restaurantcore.dto.UserDto;
import com.filrouge.restaurantcore.entity.User;

/**
 * /**
 * Personalized DAO services for User.
 * @author Hermann
 *
 */

public interface IUserRepository extends MongoRepository<User, String> {
	//The key is of type String for an identifier using the @MongoId annotation (FieldType.OBJECT_ID)
    //The key is automatically generated by MongoDB
	
	// JPQL query
	 
	  List<User> findByEmail(String email);
	  
	  
	  List<User> findByLastNameAndPassword( String lastName, String password);
	  
	  
	  List<User> findByFirstNameAndLastName(String firstName, String lastName);
	  
	


}
